[phases.setup]
nixPkgs = ["python311", "gcc", "glib", "libGL", "xorg.libSM", "xorg.libXext", "xorg.libXrender", "glibc", "libgcc"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python main.py"