[phases.setup]
nixPkgs = ["python311", "gcc", "glib", "libGL"]

[phases.install]
cmds = [
    "python -m ensurepip",
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
]

[start]
cmd = "python main.py"